// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface AboutPage {
  id: string;
  slug: string | null;
  status: string;
  page_title: string;
  url_slug?: string;
  page_subtitle?: string;
  what_is_cyberdeck_content?: PortableTextBlock[];
  community_content?: PortableTextBlock[];
  how_to_get_involved_content?: PortableTextBlock[];
  about_this_site_content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Build {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  gallery?: string;
  parts_list?: string;
  compute_platform?: string;
  estimated_cost?: number;
  difficulty?: string;
  build_time?: string;
  builder?: string;
  tags?: string;
  linked_build_log?: string;
  linked_wiki_articles?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ForumPost {
  id: string;
  slug: string | null;
  status: string;
  thread_id: string;
  content?: PortableTextBlock[];
  author?: string;
  is_deleted?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ForumThread {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  category: string;
  content?: PortableTextBlock[];
  author?: string;
  reply_count?: number;
  view_count?: number;
  is_pinned?: boolean;
  is_locked?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface HomepageConfig {
  id: string;
  slug: string | null;
  status: string;
  hero_title: string;
  hero_subtitle: string;
  get_started_btn?: string;
  join_forum_btn?: string;
  what_is_cyberdeck_title?: string;
  what_is_cyberdeck_text?: string;
  portable_label?: string;
  custom_label?: string;
  yours_label?: string;
  featured_wiki_title?: string;
  active_threads_title?: string;
  upcoming_meetups_title?: string;
  recent_builds_title?: string;
  cta_title?: string;
  cta_text?: string;
  introduce_btn?: string;
  read_wiki_btn?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface MeetupEvent {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: PortableTextBlock[];
  location_name?: string;
  location_lat?: number;
  location_lng?: number;
  date_start: string;
  date_end?: string;
  organizer?: string;
  max_attendees?: number;
  rsvp_count?: number;
  region?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Member {
  id: string;
  slug: string | null;
  status: string;
  username: string;
  email?: string;
  display_name?: string;
  avatar_url?: string;
  bio?: string;
  post_count?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface WikiArticle {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  category: string;
  content?: PortableTextBlock[];
  excerpt?: string;
  author?: string;
  view_count?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    about_page: AboutPage;
    builds: Build;
    forum_posts: ForumPost;
    forum_threads: ForumThread;
    homepage_config: HomepageConfig;
    meetup_events: MeetupEvent;
    members: Member;
    pages: Page;
    posts: Post;
    wiki_articles: WikiArticle;
  }
}